- name: Installing multiple things using loops.
  hosts: web
  become: yes
  tasks:
    - name: Installing
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
      - nginx
      - mysql
      - nodejs