# Using variables defined in .ini file

- name: "Variables from .ini file"
  hosts: local
  connection: local
  tasks:
    - name: print
      ansible.builtin.debug:
         msg: "NAME : {{ Username }} AGE : {{ Age }} HOBBY : {{ Hobby }}"