# Install nginx based on OS

- name: Install Nginx
  hosts: web
  tasks:
    - name: Installing 
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_facts.os_family == "RedHat"

    - name: Installing 
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_facts.os_family == "Debian"