- name: Check number is greater than 10
  hosts: local
  vars:
    given_num: 2
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Given numer is greater than 10"
      when: given_num | int >10  # when is used as if 

    - name: Print
      ansible.builtin.debug:
        msg: "Given number is less than or equal to 10"
      when: given_num | int <=10 
      # we are using " | int " to convert given_num to convert to integer and then 
      # compare with 10