- name: Check number is greater than 10
  hosts: local
  vars:
    num: 2
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Given numer is greater than 10"
      when: num>10  # when is used as if 

    - name: Print
      ansible.builtin.debug:
        msg: "Given number is less than or equal to 10"
      when: num<=10