- name: Filters
  hosts: local
  tasks:
    - name: Filter to provide default value
      ansible.builtin.debug:
        msg: "Hi {{ name | default('Chandan')}}  Age: {{ age | default(27) }}"

    - name: Filter to make varaibles optional.
      ansible.builtin.debug:
        msg: "Name:{{ item.name | default(omit) }} Age:{{ item.age | default(omit)}}"
      loop:
        - { name: "Chandan", age: 27 }
        - { name: "Bradley" }
        - { age: 33 }

    - name: Filter to make variables mandatory
      ansible.builtin.debug:
        msg: "Email:{{ email | mandatory }}"
    # if we don't provide variables which declared as mandatory
    #  {"msg": "Mandatory variable 'email'  not defined."}--> this error message is thrown.

    - name: Filter which can be used as if-else
      vars:
        active: true
      ansible.builtin.debug:
        msg: "{{ active | ternary('User is online','User is offline')}}"

    - name: Check number is greater than 10 or not using ternary
      vars:
        given_num: 1
      ansible.builtin.debug:
        msg: "{{ given_num>10 | ternary('Given number is greater than 10','Given number is less than or equal to 10')}}"


