- name: "Passing username and password from .ini"
  hosts: groupinghosts
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "NAME : {{ Username }} AGE : {{ Age }} HOBBY : {{ Hobby }}"


# In this we grouped both ansible server and node together using keyword children and passed ansible_user 
#  and password from .ini file